name: Docker Compose Up on Green Checkmark

on:
  push:
    branches:
      - main # Or your main branch name
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  deploy:
    if: github.event.head_commit.author.name != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Логин Docker Hub
          password: ${{ secrets.DOCKER_PASSWORD }}  # Пароль Docker Hub

      - name: Docker Build Container
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/task-bot-srv:latest .
      
      - name: Docker Push Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/task-bot-srv:latest

      - name: Deploy to VPS (via SSH)
        run: |
          sshpass -p "${{ secrets.ROOT_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
            # Загружаем образ из Docker Hub
            docker pull ${{ secrets.DOCKER_USERNAME }}/task-bot-srv:latest

            # Останавливаем и удаляем старый контейнер, если он существует
            docker stop task-bot-srv-container || true
            docker rm task-bot-srv-container || true

            # Запускаем новый контейнер с образом из Docker Hub
            docker run -d --name task-bot-srv-container -p 8081:8081 ${{ secrets.DOCKER_USERNAME }}/task-bot-srv:latest
          EOF
