name: Docker Compose Up on Green Checkmark

on:
  push:
    branches:
      - main # Or your main branch name
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  deploy:
    if: github.event.head_commit.author.name != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Логин Docker Hub
          password: ${{ secrets.DOCKER_PASSWORD }}  # Пароль Docker Hub

      - name: Docker Compose Up
        run: docker compose up --build -d
